### PR TITLE
[Welcome] Remove user avatar being set in embed by default

### PR DESCRIPTION
**Pull request by ryan-hartzell**
Fix for issue #257

### CODE REVIEW

**Comment by TrustyJAID** [comment]
This fix will break everyone who is currently relying on the default user avatar.

**Comment by ryan-hartzell** [comment]
True. I'm looking for a way to not include a thumbnail in the embed though. I guess this fix is a little heavy handed.

**Comment by TrustyJAID** [comment]
One method I have recommended in the past is set the thumbnail image to a image uploaded to discord and then delete the image. Or provide a fake/empty url instead. That will clear out the user thumnail.

**Comment by ryan-hartzell** [comment]
Okay, I can try that. Thanks!

**Pull request closed without merging**
